services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgdb
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    container_name: db_mediasoft
    ports:
      - '5433:5432'
    restart: always

volumes:
  postgres_volume: