# Generated by Django 5.0.6 on 2024-06-08 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="city",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="shops.city"
            ),
            preserve_default=False,
        ),
    ]
