# Generated by Django 5.0.6 on 2024-06-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0002_shop_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="street",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
