# Generated by Django 5.0.6 on 2024-06-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0003_alter_city_name_alter_street_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
